### ISSUE TITLE
Cloudfare

### ISSUE THREAD

**Issue by ghost** [mksanti/personal-website#2]
Hello Mike,

I saw [an issue](https://github.com/nuxt/nuxt.js/issues/1671) saying you integrated cloudflare with nuxt and github pages. After checking your code it seems it's not the case anymore. Do you have any feedbacks about this config? 

Cheers

**Comment by mksanti** [comment]
Hi @tchret, 

In my case, I had a cloudflare option enabled that removed html blocks with email.

![image](https://user-images.githubusercontent.com/5166571/64788735-7abc4b00-d549-11e9-8519-81114e797f69.png)
